### ISSUE TITLE
Check type 2 AppImages

### ISSUE THREAD

**Issue by probonopd** [orivej/static-appimage#1]
https://github.com/AppImage/AppImageSpec/blob/master/draft.md#type-2-image-format

Experimental implementation:
https://github.com/probonopd/appimagetool

The advantage of this is that there is no fixed offset for the filesystem image, which means that it is not so tightly size-restricted.

**Comment by orivej** [comment]
Thanks for referring me to the spec!

It's neat how you solved the loss of application icons in squashfs images and automated `chmod +x` with `appimaged`.

Why did you keep `chdir($mnt/usr)` in the spec and in `AppRun`? What applications benefit from this?

**Comment by probonopd** [comment]
Some applications and libraries hardcode paths in `/usr`. This is why for these, we binary patch the absolute path `/usr` to the relative path `././` which works if we cd to `$APPDIR/usr` before executing the app, and if the app does not call `chrdir()`.

There are [more elegant ways](https://github.com/probonopd/AppImageKit/issues/267) around this, but so far none of them seems to work 100% yet. Contributions in this area are highly welcome.
