### ISSUE TITLE
Can't get generated AppImage to run, permissions denied

### ISSUE THREAD

**Issue by probonopd** [orivej/static-appimage#2]
On Ubuntu 16.04 with Go 1.7, I can't get the generated AppImage to run, it says "permission denied". Can you please give very precise instructions about your build and runtime environment?
Thanks.

**Comment by orivej** [comment]
I believe the readme says it all, this print `hello`:

```sh
go get github.com/orivej/static-appimage/...
mkdir app
echo -e '#!/bin/sh\necho hello' > app/AppRun
chmod +x app/AppRun
make-static-appimage app appzip
./appzip
```

**Comment by probonopd** [comment]
Thanks, on which distro and version are you building and running this?

**Comment by orivej** [comment]
This time I used NixOS unstable, but then I reproduced permission denied with static-appimage-runtime built on Ubuntu. I'm going to investigate this.

**Comment by orivej** [comment]
I was depending on a feature of go-fuse that I forgot either to merge upstream or to vendor into static-appimage. Now it is [upstreamed](https://github.com/hanwen/go-fuse/pull/151) and you should get it working with `go get -u github.com/orivej/static-appimage/...`. I also removed dependency on a feature of Go 1.7, so static-appimage can also be be built at least with Go 1.5 and 1.6.

**Comment by probonopd** [comment]
Thank you very much, it is working now.
